### ISSUE TITLE
Breaking changes in pydantic 2.9 

### ISSUE THREAD

**Issue by dbirman** [AllenNeuralDynamics/aind-data-schema#1050]
One of several tests that fails if pydantic is updated to >=2.9

```
======================================================================
ERROR: tests.test_session (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_session
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/aind-data-schema/aind-data-schema/tests/test_session.py", line 19, in <module>
    from aind_data_schema.core.session import (
  File "/home/runner/work/aind-data-schema/aind-data-schema/src/aind_data_schema/core/session.py", line 42, in <module>
    from aind_data_schema.core.procedures import Anaesthetic, CoordinateReferenceLocation
  File "/home/runner/work/aind-data-schema/aind-data-schema/src/aind_data_schema/core/procedures.py", line 390, in <module>
    class Injection(AindModel):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_model_construction.py", line 223, in __new__
    complete_model_class(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_model_construction.py", line 568, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/main.py", line 670, in __get_pydantic_core_schema__
    return handler(source)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 924, in _generate_schema_inner
    return self._model_schema(obj)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 739, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 739, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1115, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1304, in _common_field_schema
    schema = self._apply_annotations(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2104, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2186, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2182, in <lambda>
    lambda source, handler: handler(source)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2093, in inner_handler
    return transform_inner_schema(schema)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1294, in set_discriminator
    schema = self._apply_discriminator_to_union(schema, field_info.discriminator)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 574, in _apply_discriminator_to_union
    return _discriminated_union.apply_discriminator(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_discriminated_union.py", line 97, in apply_discriminator
    return _ApplyInferredDiscriminator(discriminator, definitions or {}).apply(schema)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_discriminated_union.py", line 191, in apply
    schema = self._apply_to_root(schema)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_discriminated_union.py", line 227, in _apply_to_root
    self._handle_choice(choice)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pydantic/_internal/_discriminated_union.py", line 289, in _handle_choice
    raise TypeError(
TypeError: 'list' is not a valid discriminated union variant; should be a `BaseModel` or `dataclass`
```

**Comment by bruno-f-cruz** [comment]
I can fix it later, but basically, this is the problem i think:

https://github.com/AllenNeuralDynamics/aind-data-schema/blob/35dcab18a4e243374bdac885996e92b2e194d791/src/aind_data_schema/core/procedures.py#L393-L396

the signature is wrong, the discriminator should not be applied to the list of unions, but instead to the union type itself.

**Comment by bruno-f-cruz** [comment]
@jtyoung84 had flagged it https://github.com/AllenNeuralDynamics/aind-data-schema/issues/765

**Comment by jtyoung84** [comment]
It's possible this line here may be causing problems: https://github.com/AllenNeuralDynamics/aind-data-schema/blob/0104e43068841263aed63aacb46042b416e4b2c8/src/aind_data_schema/core/metadata.py#L126
For the Metadata class, I don't want to raise any errors if an invalid sub-model like procedures is passed into it, but maybe I should just attach a dict instead of using `model_construct`?

**Comment by bruno-f-cruz** [comment]
Tracking https://github.com/pydantic/pydantic/issues/10344 as a relevant issue for the `model_construct` pattern.
